name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '4', '6', '8', '10', '12', '14', '16' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: ./preinstall.sh
      - run: npm install
      - run: npm test
      - run: npm run coveralls